---
- name: Check for hostname
  ansible.builtin.command: hostname -f
  register: hostname1
  changed_when: false

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Check for hostname2
  ansible.builtin.command: hostname -f
  register: hostname2
  changed_when: false

- name: Check if resolv.conf is correctly set up
  ansible.builtin.replace:
    path: /etc/resolv.conf
    regexp: '.*nameserver.*'
    replace: 'nameserver {{ dns_ip }}'
  # register: command_result
  # failed_when:  if the command chattr +i has already been executed this throw error

- name: Add hostname to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    search_string: '127.0.0.1'
    line: 127.0.0.1 {{ inventory_hostname }} localhost

- name: Execute command chattr +i /etc/resolv.conf # to prevent Network manager from overridind the file
  ansible.builtin.command: chattr +i /etc/resolv.conf
  changed_when: false

- name: Reboot the server
  ansible.builtin.shell: "sleep 5 && reboot"
  tags: reboot
  become: true
  become_user: root
  async: 1
  poll: 0
  changed_when: true

- name: Wait for the reboot to complete if there was a change
  ansible.builtin.wait_for_connection:
    connect_timeout: 10
    sleep: 5
    delay: 5
    timeout: 300
...
